baseURL = "https://h4ckr00t.com"
languageCode = "en-us"
title = "H4ck R007"
theme = "m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/posts/about/"
    weight = 3

[params]
  author = "H4ck R00t"
  description = "A blog about all things offensive security, Tech and Programming. Cybersecurity (CTFs, OverTheWire, HackTheBox Labs, Tools , Tips)"
  
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ogdmerlin"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ogdmerlinn"
